#!/bin/bash -x
#SBATCH --job-name=ising
#SBATCH --mail-type=ALL
#SBATCH --mail-user=s6chgros@uni-bonn.de
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --mem=500mb
#SBATCH --time=01:30:00
#SBATCH --output=outanderror/ising-%j.out
#SBATCH --error=outanderror/errorising-%j.out
#SBATCH --nodelist=lcpunode02

export OMP_NUM_THREAD=${SLURM_CPUS_PER_TASK}
export KMP_AFFINITY=balanced,granularity=fine,verbose

cd /hiskp4/gross/bachelorarbeit

srun /hiskp4/gross/bachelorarbeit/ising

cd -
