#!/bin/bash -x
#SBATCH --job-name=skalierungmpi
#SBATCH --mail-type=ALL
#SBATCH --mail-user=s6chgros@uni-bonn.de
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=50mb
#SBATCH --time=00:10:00
#SBATCH --output=outanderror/skalierungmpi-%j.out
#SBATCH --error=outanderror/errorskalierungmpi-%j.out

export KMP_AFFINITY=balanced,granularity=fine,verbose

cd /hiskp4/gross/bachelorarbeit

laenge=$1
temperatur=$2
merkmal=$3
nodes=$4
srun -n1 /hiskp4/gross/bachelorarbeit/mpiskalierung ${laenge} ${temperatur} ${merkmal}

cd -
#Skript, um das Programm, das Laufzeitskalierung der messenmpifunktion misst, auszufuehren
