#!/bin/bash -x
#SBATCH --job-name=grosstest1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=s6chgros@uni-bonn.de
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=50mb
#SBATCH --time=00:05:00
#SBATCH --output=outanderror/test1.%J.out
#SBATCH --error=outanderror/test1error.%J.out
#SBATCH --nodelist=lcpunode01

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
export KMP_AFFINITY=balnce,granularity=fine,verbose

cd /hiskp4/gross/bachelorarbeit

srun /hiskp4/gross/bachelorarbeit/ising

cd -
