#!/bin/bash -x
#SBATCH --job-name=skalfak
#SBATCH --mail-type=ALL
#SBATCH --mail-user=s6chgros@uni-bonn.de
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=20mb
#SBATCH --time=00:30:00
#SBATCH --output=outanderror/skalfak-%j.out
#SBATCH --error=outanderror/errorskalfak-%j.out
#SBATCH --nodelist=lcpunode01

export OMP_NUM_THREAD=${SLURM_CPUS_PER_TASK}
export KMP_AFFINITY=balanced,granularity=fine,verbose

cd /hiskp4/gross/bachelorarbeit

srun /hiskp4/gross/bachelorarbeit/skalfak01

cd -

#Messung der Skalierung der Fakultaetsfunktion auf lcpunode01
